name: dl_hw_05p39
channels:
  - pytorch
  - defaults
dependencies:
- python=3.9.6.
- pillow
- matplotlib
- numpy
- "pytorch>=1.6.0"
- "torchvision>=0.7.0"
- "tensorboard>=1.14"
- future
# - PySuperTuxKart
